version: '3'
services:
  web:
    container_name: user-center-client
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    env_file:
      - .env
    volumes:
      - './ssl:/etc/nginx/cert'
